name: "dependency demo"

on:
    workflow_dispatch: 
jobs:
    job-1:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "This is the first job"
    job-2:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "This is the second job"
    job-3:
        runs-on: ubuntu-22.04
        needs:
            - job-1
            - job-2
        steps:
            - run: echo "This is the third job"
    job-4:
        runs-on: ubuntu-22.04
        needs: 
            - job-3
        steps:
            - run: echo "This is the fourth job"