name: "pull-request-trigger"

on:
    pull_request: 
        types: 
            - opened
        paths: 
            - "test/*.md"
jobs:
    echo-event:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "yea u made a pull request with an md in the test dir"
            - run: echo "your event name is $GITHUB_EVENT_NAME"